//
//  SimulatorResultViewControllerTests.swift
//  easySimulator
//
//  Created by Tiago Chaves on 26/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import easySimulator
import XCTest

class SimulatorResultViewControllerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SimulatorResultViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        window = UIWindow()
        setupSimulatorResultViewController()
    }
    
    override func tearDown()
    {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSimulatorResultViewController()
    {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "SimulatorResultViewController") as! SimulatorResultViewController
    }
    
    func loadView()
    {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class SimulatorResultBusinessLogicSpy: SimulatorResultBusinessLogic, SimulatorResultDataStore
    {
        var simulationResult: SimulationResult?
        var getSimulationResultCalled = false
        
        func getSimulationResult() {
            
            getSimulationResultCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShouldGetSimulationresultWhenViewIsLoaded(){
        // Given
        let interactorSpy = SimulatorResultBusinessLogicSpy()
        interactorSpy.simulationResult = Seeds.SimulationResults.simulationResult
        sut.interactor = interactorSpy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(interactorSpy.getSimulationResultCalled, "viewDidLoad() should ask the interactor to get simulation result")
    }
    
    func testDisplaySimulationResultShouldDisplayFormattedResulInTextFields(){
        
        let interactorSpy = SimulatorResultBusinessLogicSpy()
        interactorSpy.simulationResult = Seeds.SimulationResults.simulationResult
        sut.interactor = interactorSpy
        let viewModel = SimulatorResult.GetSimulationResult.ViewModel(displayResult: Seeds.SimulationResults.simulationResultDisplay)
        
        loadView()
        sut.displaySimulationResult(viewModel: viewModel)
        
        let expectGrossAmount = expectation(description: "Wait for update gross amount label")
        let observeGrossAmount = sut.grossAmountLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.grossAmount
            
            // Then
            XCTAssertEqual(expected, self.sut.grossAmountLabel.text!, "gross amount label should display formatted amount string - \(expected)")
            expectGrossAmount.fulfill()
        }
        
        let expectTaxes = expectation(description: "Wait for update taxes label")
        let observeTaxes = sut.taxesLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.taxesAmount + "(" + viewModel.displayResult.taxesRate + ")"
            
            // Then
            XCTAssertEqual(expected, self.sut.taxesLabel.text!, "taxes label should display formatted amount string - \(expected)")
            expectTaxes.fulfill()
        }
        
        let expectNetAmount = expectation(description: "Wait for update net amount label")
        let observeNetAmount = sut.netAmountLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.netAmount
            
            // Then
            XCTAssertEqual(expected, self.sut.netAmountLabel.text!, "net amount label should display formatted amount string - \(expected)")
            expectNetAmount.fulfill()
        }
        
        let expectGrossAmountProfit = expectation(description: "Wait for update gross amount profit label")
        let observeGrossAmountProfit = sut.grossAmountProfitLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.grossAmountProfit
            
            // Then
            XCTAssertEqual(expected, self.sut.grossAmountProfitLabel.text!, "gross amount profit label should display formatted amount string - \(expected)")
            expectGrossAmountProfit.fulfill()
        }
        
        let expectAnnualGrossRateProfit = expectation(description: "Wait for update annual gross rate profit label")
        let observeAnnualGrossRateProfit = sut.annualGrossRateProfitLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.annualGrossRateProfit
            
            // Then
            XCTAssertEqual(expected, self.sut.annualGrossRateProfitLabel.text!, "annual gross rate profit label should display formatted amount string - \(expected)")
            expectAnnualGrossRateProfit.fulfill()
        }
        
        let expectMonthlyGrossRateProfit = expectation(description: "Wait for update monthly gross rate profit label")
        let observeMonthlyGrossRateProfit = sut.monthlyGrossRateProfitLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.monthlyGrossRateProfit
            
            // Then
            XCTAssertEqual(expected, self.sut.monthlyGrossRateProfitLabel.text!, "monthly gross rate profit label should display formatted amount string - \(expected)")
            expectMonthlyGrossRateProfit.fulfill()
        }
        
        let expectRateProfit = expectation(description: "Wait for update rate profit label")
        let observeRateProfit = sut.rateProfitLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.rateProfit
            
            // Then
            XCTAssertEqual(expected, self.sut.rateProfitLabel.text!, "rate profit label should display formatted amount string - \(expected)")
            expectRateProfit.fulfill()
        }
        
        let expectInvestedAmount = expectation(description: "Wait for update invested amount label")
        let observeInvestedAmount = sut.investedAmountLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.investedAmount
            
            // Then
            XCTAssertEqual(expected, self.sut.investedAmountLabel.text!, "invested amount label should display formatted amount string - \(expected)")
            expectInvestedAmount.fulfill()
        }
        
        let expectMaturityTotalDays = expectation(description: "Wait for update maturity total days label")
        let observeMaturityTotalDays = sut.maturityTotalDaysLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.maturityTotalDays
            
            // Then
            XCTAssertEqual(expected, self.sut.maturityTotalDaysLabel.text!, "maturity total days label should display formatted amount string - \(expected)")
            expectMaturityTotalDays.fulfill()
        }
        
        let expectMaturityDate = expectation(description: "Wait for update maturity date label")
        let observeMaturityDate = sut.maturityDateLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.maturityDate
            
            // Then
            XCTAssertEqual(expected, self.sut.maturityDateLabel.text!, "maturity date label should display formatted amount string - \(expected)")
            expectMaturityDate.fulfill()
        }
        
        let expectRate = expectation(description: "Wait for update rate label")
        let observeRate = sut.rateLabel.observe(\.text, options: [.new]) { (label, value) in
            
            let expected = viewModel.displayResult.rate
            
            // Then
            XCTAssertEqual(expected, self.sut.rateLabel.text!, "rate label should display formatted amount string - \(expected)")
            expectRate.fulfill()
        }
        
        waitForExpectations(timeout: 5.0)
       
    }
}
