//
//  SimulatorResultInteractor.swift
//  easySimulator
//
//  Created by Tiago Chaves on 23/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SimulatorResultBusinessLogic
{
    func getSimulationResult()
}

protocol SimulatorResultDataStore
{
    var simulationResult: SimulationResult? { get set }
}

class SimulatorResultInteractor: SimulatorResultBusinessLogic, SimulatorResultDataStore
{
    var simulationResult: SimulationResult?
    var presenter: SimulatorResultPresentationLogic?
    var worker: SimulatorResultWorker?
    
    // MARK: Do something
    
    func getSimulationResult()
    {
        let response = SimulatorResult.GetSimulationResult.Response(simulationResult: simulationResult!)
        presenter?.presentSimulationResult(response: response)
    }
}
