//
//  SimulatorResultModels.swift
//  easySimulator
//
//  Created by Tiago Chaves on 23/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SimulatorResult
{
    // MARK: Use cases
    
    enum GetSimulationResult
    {
        struct Request
        {
            
        }
        struct Response
        {
            var simulationResult:SimulationResult
        }
        struct ViewModel
        {
            var displayResult:DisplaySimulationResult
        }
    }
}

struct DisplaySimulationResult {
    let investedAmount:String
    let grossAmount:String
    let grossAmountProfit:String
    let taxesAmount:String
    let taxesRate:String
    let netAmount:String
    
    let maturityDate:String
    let maturityTotalDays:String
    let monthlyGrossRateProfit:String
    let rate:String
    let annualGrossRateProfit:String
    let rateProfit:String
}
