# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'easySimulator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for easySimulator
  pod 'SwiftLint'

  target 'easySimulatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'easySimulatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
