//
//  SimulatorInputWorkerTests.swift
//  easySimulator
//
//  Created by Tiago Chaves on 26/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import easySimulator
import XCTest

class SimulatorInputWorkerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SimulatorInputWorker!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupSimulatorInputWorker()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSimulatorInputWorker()
    {
        sut = SimulatorInputWorker(SimulatorNetworkWorkerSpy())
    }
    
    // MARK: Test doubles
    
    class SimulatorNetworkWorkerSpy:SimulatorNetworkWorker {
        
        var simulatorNetworkCalled = false
        override func getSimulationResult(withInvestedAmount investedAmount: Double, rate: Int, andMaturityDate maturityDate: Date, completionHandler: @escaping (() throws -> SimulationResult) -> Void) {
            
            simulatorNetworkCalled = true
            DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) {
                
                completionHandler { return Seeds.SimulationResults.simulationResult }
            }
        }
    }
    
    // MARK: Tests
    
    func testGetSimulationShouldBeReturnedFromAPI() {
        
        let simulatorNetworkSpy = sut.worker as! SimulatorNetworkWorkerSpy
        
        let expect = expectation(description: "Wait for simulation result to return")
        sut.getSimulationResult(withInvestedAmount: 123.0, rate: 123, andMaturityDate: Date(), completionHandler: { (result, error) in
            expect.fulfill()
        })
        waitForExpectations(timeout: 1.1)
        
        XCTAssertTrue(simulatorNetworkSpy.simulatorNetworkCalled, "simulation result should ask API for a simulation")
    }
}
