//
//  SimulatorInputModels.swift
//  easySimulator
//
//  Created by Tiago Chaves on 22/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SimulatorInput
{
  // MARK: Use cases
  
    enum Simulation
    {
        struct Request
        {
            var investedAmount:String
            var rate:String
            var maturityDate:Date
        }
        struct Response
        {
            var result:SimulationResult?
            var error:Error?
        }
        struct ViewModel
        {
            var success:Bool
        }
    }
    
    enum FormatMaturityDate
    {
        struct Request
        {
            var maturityDate:Date
        }
        struct Response
        {
            var maturityDate:Date
        }
        struct ViewModel
        {
            var formatedMaturityDate:String
        }
    }
    
    enum FormatNumericField
    {
        enum NumericFieldTypes{
            case amount(Int)
            case rate(Int)
        }
        
        struct Request
        {
            var value:String
            var fieldType:NumericFieldTypes
        }
        struct Response
        {
            var value:String
            var fieldType:NumericFieldTypes
        }
        struct ViewModel
        {
            var formatedValue:String
            var tag:Int
        }
    }
}
