//
//  SimulatorInputModels.swift
//  easySimulator
//
//  Created by Tiago Chaves on 22/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SimulatorInput
{
  // MARK: Use cases
  
  enum Simulation
  {
    struct Request
    {
        var investedAmount:Double
        var rate:Int
        var maturityDate:Date
    }
    struct Response
    {
        var result:SimulationResult?
        var error:Error?
    }
    struct ViewModel
    {
        var success:Bool
    }
  }
}
