//
//  SimulatorInputWorker.swift
//  easySimulator
//
//  Created by Tiago Chaves on 22/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SimulatorInputWorker{
    var worker:SimulatorInputWorkerProtocol
    
    init(_ worker:SimulatorInputWorkerProtocol) {
        self.worker = worker
    }
    
    func getSimulationResult(withInvestedAmount investedAmount:Double, rate:Int, andMaturityDate maturityDate:Date, completionHandler:@escaping (SimulationResult?,Error?) -> Void) {
        worker.getSimulationResult(withInvestedAmount: investedAmount, rate: rate, andMaturityDate: maturityDate) { (simulationResult: () throws -> SimulationResult) -> Void in
            do{
                let simulationResult = try simulationResult()
                completionHandler(simulationResult,nil)
            }catch let error{
                completionHandler(nil,error)
            }
        }
    }
}

protocol SimulatorInputWorkerProtocol {
    func getSimulationResult(withInvestedAmount investedAmount:Double, rate:Int, andMaturityDate maturityDate:Date, completionHandler:@escaping (() throws -> SimulationResult) -> Void)
}

enum SimulationError: Error {
    case cannotSimulate(String)
}
