//
//  SimulatorInputPresenter.swift
//  easySimulator
//
//  Created by Tiago Chaves on 22/08/2018.
//  Copyright (c) 2018 easynvest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SimulatorInputPresentationLogic
{
  func presentSimulationResult(response: SimulatorInput.Simulation.Response)
}

class SimulatorInputPresenter: SimulatorInputPresentationLogic
{
  weak var viewController: SimulatorInputDisplayLogic?
  
  // MARK: Do something
  
  func presentSimulationResult(response: SimulatorInput.Simulation.Response)
  {
    let viewModel = SimulatorInput.Simulation.ViewModel(success: (response.error == nil))
    viewController?.displaySimulationResult(viewModel: viewModel)
  }
}
